Remove -Werror for clang build
... due to (new) error in Eigen:
/usr/include/eigen3/Eigen/src/LU/arch/Inverse_SSE.h:142:45: error: cast from 'const unsigned int *' to 'float *' drops const qualifier [-Werror,-Wcast-qual]