use clang for clang-tidy job
And add warnings for gcc AND clang builds (as they can differ slightly).

Clang does not support -Wused-but-set-parameter yet, though
support is [on the way](https://reviews.llvm.org/D100581).
So this gets rid of this warning we see in CI:

> error: unknown warning option '-Wno-unused-but-set-parameter'; did you mean '-Wno-unused-parameter'?