explicitly instantiate template for required values
Fixup for 10f6b7a58ed6063771eb7b9cbe9931fc71497ca8 .

On my release workspace I see
/usr/bin/ld: libmoveit_task_constructor_core_stages.so: undefined reference to `
void moveit::task_constructor::PropagatingEitherWay::send<(moveit::task_constructor::Interface::Direction)0>(moveit::task_constructor::InterfaceState const&, moveit::task_constructor::InterfaceState&&, moveit::task_constructor::SubTrajectory&&)'
/usr/bin/ld: libmoveit_task_constructor_core_stages.so: undefined reference to `
void moveit::task_constructor::PropagatingEitherWay::send<(moveit::task_constructor::Interface::Direction)1>(moveit::task_constructor::InterfaceState const&, moveit::task_constructor::InterfaceState&&, moveit::task_constructor::SubTrajectory&&)'

It seems the methods can be inlined and (and symbols dropped) in gcc with optimizations on.